-----

## Actividad Entregable

1. Crea un arreglo 5x3 de números aleatorios entre 0 y 100
2. ¿Cuál es la suma total de los valores del arreglo?
3. ¿Cúal es el promedio de cada columna del arreglo?
4. Crea una matriz 10x10 de enteros aleatorios (0-9).
5. Pon en -1 todos los valores > 5
6. Abre una imagen, muestra shape, min, max y promedio de cada canal

In [22]:

import numpy as np                 
import matplotlib.pyplot as plt  

# 1. Crea un arreglo 5x3 de números aleatorios entre 0 y 100
arreglo = np.random.randint(0, 101, size=(5, 3))
print( arreglo)



[[ 2 50 40]
 [38 79 12]
 [76 29  3]
 [81 64 57]
 [57 49 29]]


In [23]:
# 2. ¿Cuál es la suma total de los valores del arreglo?
suma_total = arreglo.sum()
print("Suma total:", suma_total)



Suma total: 666


In [24]:
# 3. ¿Cuál es el promedio de cada columna del arreglo?
promedio_columnas = arreglo.mean(axis=0)  # axis=0 significa "por columnas"
print("Promedio de cada columna:", promedio_columnas)



Promedio de cada columna: [50.8 54.2 28.2]


In [25]:
# 4. Crea una matriz 10x10 de enteros aleatorios (0-9)
matriz = np.random.randint(0, 10, size=(10, 10))
print("Matriz 10x10\n", matriz)



Matriz 10x10
 [[7 3 4 1 1 1 4 6 8 1]
 [8 3 9 5 5 3 3 3 6 3]
 [9 4 2 9 5 4 2 8 1 2]
 [0 2 0 0 1 4 7 7 3 9]
 [4 0 6 1 1 5 6 9 7 0]
 [1 9 4 7 2 7 2 0 2 5]
 [6 5 6 5 9 0 3 5 6 3]
 [5 1 0 4 5 6 1 0 7 1]
 [4 0 2 5 9 7 2 9 7 5]
 [2 1 8 8 0 9 4 9 5 9]]


In [26]:
# 5. Pon en -1 todos los valores > 5
matriz[matriz > 5] = -1
print("\nMatriz con valores > 5 cambiados a -1:\n", matriz)




Matriz con valores > 5 cambiados a -1:
 [[-1  3  4  1  1  1  4 -1 -1  1]
 [-1  3 -1  5  5  3  3  3 -1  3]
 [-1  4  2 -1  5  4  2 -1  1  2]
 [ 0  2  0  0  1  4 -1 -1  3 -1]
 [ 4  0 -1  1  1  5 -1 -1 -1  0]
 [ 1 -1  4 -1  2 -1  2  0  2  5]
 [-1  5 -1  5 -1  0  3  5 -1  3]
 [ 5  1  0  4  5 -1  1  0 -1  1]
 [ 4  0  2  5 -1 -1  2 -1 -1  5]
 [ 2  1 -1 -1  0 -1  4 -1  5 -1]]


In [29]:
# 6. Abre una imagen, muestra shape, min, max y promedio de cada canal
## Uso la imagen de mi pérrito ORION
from PIL import Image

imagen = Image.open("imagen.jpg")
imagen.show()

## tuve qeu crear esto por que me decia que la imagen no tenia atributo de shape
imagen = np.array(imagen_pil) 
imagen_pil = Image.open("imagen.jpg")
print("\nShape de la imagen:", imagen.shape)

## Tuve qeu buscar el indice de cada color, como es RGB va de 0 a 2
'''
| Canal | Índice |
| ----- | ------ |
| Rojo  | 0      |
| Verde | 1      |
| Azul  | 2      |
'''
rojo = imagen[:, :, 0]
verde = imagen[:, :, 1]
azul = imagen[:, :, 2]


## Aca lo hice todo en una linea para mostrar min max y promedio de cada canal

# Mostrar Min, Max y promedio del canal rojo
print("Canal Rojo - Min:", rojo.min(), "Max:", rojo.max(), "Promedio:", rojo.mean())

# Mostrar Min, Max y promedio del canal verde
print("Canal Verde - Min:", verde.min(), "Max:", verde.max(), "Promedio:", verde.mean())

# Mostrar Min, Max y promedio del canal azul
print("Canal Azul - Min:", azul.min(), "Max:", azul.max(), "Promedio:", azul.mean())


Shape de la imagen: (2048, 1536, 4)
Canal Rojo - Min: 0 Max: 255 Promedio: 62.88367017110189
Canal Verde - Min: 0 Max: 255 Promedio: 53.65399932861328
Canal Azul - Min: 0 Max: 255 Promedio: 46.06454372406006
